"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Status = "checking" | "ready" | "invalid";

export default function ResetPasswordPage() {
  const [status, setStatus] = useState<Status>("checking");
  const [password, setPassword] = useState("");
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(false);
  const [debugError, setDebugError] = useState("");

  useEffect(() => {
    const supabase = createClient();

    // The recovery link (generated by admin.auth.generateLink({ type:
    // "recovery" }) in /api/auth/request-reset) lands here with the session
    // tokens in the URL's hash fragment (#access_token=...&refresh_token=...
    // — Supabase's older implicit-flow format for links it generates
    // server-side). createBrowserClient from @supabase/ssr defaults to the
    // PKCE flow, which only auto-detects a `?code=` query param, NOT this
    // hash fragment — its automatic detection silently never fires for a
    // recovery link, confirmed by testing this exact flow end to end before
    // finding the fix. So this parses the fragment directly and establishes
    // the session explicitly instead of waiting on auto-detection.
    const hash = new URLSearchParams(window.location.hash.slice(1));
    const accessToken = hash.get("access_token");
    const refreshToken = hash.get("refresh_token");

    if (accessToken && refreshToken) {
      supabase.auth.setSession({ access_token: accessToken, refresh_token: refreshToken }).then(({ error }) => {
        if (error) console.error("setSession failed:", error.message, error);
        setStatus(error ? "invalid" : "ready");
        setDebugError(error?.message ?? "");
      });
    } else {
      setStatus("invalid");
    }
  }, []);

  async function handleSubmit(event: React.FormEvent) {
    event.preventDefault();
    setLoading(true);
    setMessage("");

    try {
      const supabase = createClient();
      const { error } = await supabase.auth.updateUser({ password });
      if (error) {
        setMessage(error.message);
        setLoading(false);
        return;
      }
      window.location.href = "/";
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "Something went wrong.");
      setLoading(false);
    }
  }

  return (
    <main className="grid min-h-screen place-items-center px-6">
      <section className="w-full max-w-md rounded-2xl border border-slate-800 bg-slate-900 p-8">
        <p className="text-sm uppercase tracking-[0.2em] text-slate-400">WebGenie AI</p>
        <h1 className="mt-3 text-3xl font-semibold">Set a new password</h1>

        {status === "checking" ? <p className="mt-4 text-sm text-slate-400">Checking your link…</p> : null}

        {status === "ready" ? (
          <form onSubmit={handleSubmit} className="mt-8 space-y-4">
            <label className="block">
              <span className="text-sm text-slate-300">New password</span>
              <input
                type="password"
                required
                minLength={8}
                autoComplete="new-password"
                value={password}
                onChange={(event) => setPassword(event.target.value)}
                className="mt-2 w-full rounded-lg px-3 py-2"
                placeholder="••••••••"
              />
            </label>
            <button
              disabled={loading}
              className="w-full rounded-lg bg-white px-4 py-2 font-medium text-slate-950 disabled:opacity-60"
            >
              {loading ? "Please wait…" : "Set password and continue"}
            </button>
          </form>
        ) : null}

        {status === "invalid" ? (
          <p className="mt-4 text-sm text-slate-400">
            This link is invalid or has expired. <a href="/forgot-password" className="underline decoration-dotted underline-offset-4">Request a new one</a>.
            {debugError ? <span className="mt-2 block text-xs text-rose-400">{debugError}</span> : null}
          </p>
        ) : null}

        {message ? <p className="mt-4 text-sm text-slate-300">{message}</p> : null}
      </section>
    </main>
  );
}
