"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Status = "checking" | "ready" | "invalid";

export default function ResetPasswordPage() {
  const [status, setStatus] = useState<Status>("checking");
  const [password, setPassword] = useState("");
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const supabase = createClient();

    // The recovery link (generated by generateLink({ type: "recovery" }) in
    // /api/auth/request-reset) lands here with the session tokens in the URL
    // fragment. The browser client auto-detects that on load and fires this
    // event once the recovery session is actually established — checking
    // getSession() immediately on mount can race ahead of that, so "checking"
    // is the default state rather than assuming invalid until proven otherwise.
    const { data: subscription } = supabase.auth.onAuthStateChange((event) => {
      if (event === "PASSWORD_RECOVERY") setStatus("ready");
    });

    supabase.auth.getSession().then(({ data }) => {
      if (data.session) setStatus("ready");
    });

    // Give the URL-fragment detection a few seconds before concluding the
    // link genuinely has no valid session attached.
    const timeout = setTimeout(() => {
      setStatus((current) => (current === "checking" ? "invalid" : current));
    }, 4000);

    return () => {
      subscription.subscription.unsubscribe();
      clearTimeout(timeout);
    };
  }, []);

  async function handleSubmit(event: React.FormEvent) {
    event.preventDefault();
    setLoading(true);
    setMessage("");

    try {
      const supabase = createClient();
      const { error } = await supabase.auth.updateUser({ password });
      if (error) {
        setMessage(error.message);
        setLoading(false);
        return;
      }
      window.location.href = "/";
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "Something went wrong.");
      setLoading(false);
    }
  }

  return (
    <main className="grid min-h-screen place-items-center px-6">
      <section className="w-full max-w-md rounded-2xl border border-slate-800 bg-slate-900 p-8">
        <p className="text-sm uppercase tracking-[0.2em] text-slate-400">WebGenie AI</p>
        <h1 className="mt-3 text-3xl font-semibold">Set a new password</h1>

        {status === "checking" ? <p className="mt-4 text-sm text-slate-400">Checking your link…</p> : null}

        {status === "ready" ? (
          <form onSubmit={handleSubmit} className="mt-8 space-y-4">
            <label className="block">
              <span className="text-sm text-slate-300">New password</span>
              <input
                type="password"
                required
                minLength={8}
                autoComplete="new-password"
                value={password}
                onChange={(event) => setPassword(event.target.value)}
                className="mt-2 w-full rounded-lg px-3 py-2"
                placeholder="••••••••"
              />
            </label>
            <button
              disabled={loading}
              className="w-full rounded-lg bg-white px-4 py-2 font-medium text-slate-950 disabled:opacity-60"
            >
              {loading ? "Please wait…" : "Set password and continue"}
            </button>
          </form>
        ) : null}

        {status === "invalid" ? (
          <p className="mt-4 text-sm text-slate-400">
            This link is invalid or has expired. <a href="/forgot-password" className="underline decoration-dotted underline-offset-4">Request a new one</a>.
          </p>
        ) : null}

        {message ? <p className="mt-4 text-sm text-slate-300">{message}</p> : null}
      </section>
    </main>
  );
}
