"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";
import { Panel } from "@/components/ui";
import { Logo } from "@/components/shell";

type Status = "checking" | "ready" | "invalid";

export default function ResetPasswordPage() {
  const [status, setStatus] = useState<Status>("checking");
  const [password, setPassword] = useState("");
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const supabase = createClient();

    // The recovery link (generated by admin.auth.generateLink({ type:
    // "recovery" }) in /api/auth/request-reset) lands here with the session
    // tokens in the URL's hash fragment (#access_token=...&refresh_token=...
    // — Supabase's older implicit-flow format for links it generates
    // server-side). createBrowserClient from @supabase/ssr defaults to the
    // PKCE flow, which only auto-detects a `?code=` query param, NOT this
    // hash fragment — its automatic detection silently never fires for a
    // recovery link, confirmed by testing this exact flow end to end before
    // finding the fix. So this parses the fragment directly and establishes
    // the session explicitly instead of waiting on auto-detection.
    const hash = new URLSearchParams(window.location.hash.slice(1));
    const accessToken = hash.get("access_token");
    const refreshToken = hash.get("refresh_token");

    if (accessToken && refreshToken) {
      supabase.auth.setSession({ access_token: accessToken, refresh_token: refreshToken }).then(({ error }) => {
        setStatus(error ? "invalid" : "ready");
      });
    } else {
      setStatus("invalid");
    }
  }, []);

  async function handleSubmit(event: React.FormEvent) {
    event.preventDefault();
    setLoading(true);
    setMessage("");

    try {
      const supabase = createClient();
      const { error } = await supabase.auth.updateUser({ password });
      if (error) {
        setMessage(error.message);
        setLoading(false);
        return;
      }
      window.location.href = "/";
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "Something went wrong.");
      setLoading(false);
    }
  }

  return (
    <main className="grid min-h-screen place-items-center px-6">
      <Panel className="w-full max-w-md">
        <Logo />
        <h1 className="mt-6 text-display-md font-semibold text-ink">Set a new password</h1>

        {status === "checking" ? <p className="mt-4 text-sm text-muted">Checking your link…</p> : null}

        {status === "ready" ? (
          <form onSubmit={handleSubmit} className="mt-8 space-y-4">
            <label className="block">
              <span className="text-sm text-muted">New password</span>
              <input
                type="password"
                required
                minLength={8}
                autoComplete="new-password"
                value={password}
                onChange={(event) => setPassword(event.target.value)}
                className="focus-ring mt-2 w-full rounded-lg border border-hairline bg-white px-3 py-2 text-[13px] text-slate-900 placeholder:text-slate-400"
                placeholder="••••••••"
              />
            </label>
            <button
              disabled={loading}
              className="focus-ring inline-flex w-full items-center justify-center gap-2 rounded-xl bg-iris px-4 py-2.5 text-sm font-medium text-white shadow-[0_8px_28px_-12px_rgba(124,92,255,0.9)] transition-all duration-200 hover:bg-iris-soft disabled:opacity-60"
            >
              {loading ? "Please wait…" : "Set password and continue"}
            </button>
          </form>
        ) : null}

        {status === "invalid" ? (
          <p className="mt-4 text-sm text-muted">
            This link is invalid or has expired.{" "}
            <Link href="/forgot-password" className="text-ink underline decoration-dotted underline-offset-4 hover:text-iris-soft">
              Request a new one
            </Link>
            .
          </p>
        ) : null}

        {message ? <p className="mt-4 text-sm text-signal-bad">{message}</p> : null}
      </Panel>
    </main>
  );
}
