import type { WebsiteBlueprint } from "@/lib/blueprint/types";
import type { ContentPackage } from "@/lib/copy/types";
import type { OrchestrationRunOutput } from "@/lib/orchestration/types";
import type { PromptPackage } from "@/lib/prompts/types";
import { deliveryTargetProfiles } from "./adapters";
import type { DeliveryFile, DeliveryPackage, DeliveryTarget } from "./types";

interface DeliveryInput {
  deliveryId: string;
  project: { id: string; name: string; industry: string; primaryGoal: string; primaryCta: string };
  target: DeliveryTarget;
  blueprintId: string;
  blueprint: WebsiteBlueprint;
  contentPackageId?: string;
  content?: ContentPackage;
  promptPackageId?: string;
  prompts?: PromptPackage;
  orchestrationRunId?: string;
  orchestration?: OrchestrationOutput;
}

function jsonFile(path: string, value: unknown, purpose: string): DeliveryFile {
  return { path, content: JSON.stringify(value, null, 2), contentType: "json", purpose };
}

function markdownFile(path: string, content: string, purpose: string): DeliveryFile {
  return { path, content, contentType: "markdown", purpose };
}

function buildReadme(input: DeliveryInput): string {
  const profile = deliveryTargetProfiles[input.target];
  return `# ${input.project.name} — WebGenie Implementation Handoff\n\n` +
    `Target: **${profile.label}**\n\n` +
    `This package contains the approved strategy, website blueprint, generated content, builder prompts, specialist review, and deployment instructions available for this project.\n\n` +
    `## Primary outcome\n${input.project.primaryGoal}\n\n` +
    `## Primary CTA\n${input.project.primaryCta}\n\n` +
    `## Recommended execution order\n\n` +
    `1. Review \`webgenie/manifest.json\`.\n2. Read \`webgenie/blueprint.json\`.\n3. Apply content from \`webgenie/content.json\` when included.\n4. Follow the target-specific file in \`handoff/\`.\n5. Run quality checks before production deployment.\n\n` +
    `Generated by WebGenie AI. Treat placeholders and unsupported claims as items requiring owner verification.`;
}

function targetHandoff(target: DeliveryTarget, projectName: string): string {
  const common = `# ${deliveryTargetProfiles[target].label} Handoff\n\nProject: **${projectName}**\n\n`;
  const instructions: Record<DeliveryTarget, string> = {
    download: "Use this archive as the canonical transfer package. Import the artifacts into the selected development environment and record implementation milestones in WebGenie.",
    github: "Create or select the destination repository, preserve the included directory structure, commit the files serially, and protect the production branch. The optional GitHub publisher uses the repository contents endpoint when credentials are configured.",
    vercel: "Connect the implementation repository to the intended Vercel project. Confirm framework detection, environment variables, build command, preview deployment, and production domain before promotion.",
    netlify: "Connect the implementation repository or upload the completed site bundle. Confirm the build command, publish directory, environment variables, preview deploy, and production domain.",
    bolt: "Start with the master prompt. Submit supporting prompts in the numbered order. Add the blueprint and content JSON as project context, then verify each page against the quality checklist.",
    lovable: "Create the project from the master prompt, apply design and component instructions next, connect data/auth only where required, then run the testing prompt before publishing.",
    framer: "Build global styles and components first, create the sitemap pages, apply the page copy, configure CMS collections where relevant, then complete SEO, accessibility, forms, and responsive checks.",
    claude_code: "Open the target repository, place CLAUDE.md at the root, ask Claude Code to inspect the repository before editing, and execute the implementation plan in small verified commits."
  };
  return common + instructions[target] + "\n\n## Completion gates\n\n- All required pages implemented\n- Primary conversion path tested\n- Mobile and keyboard review completed\n- Metadata and schema validated\n- Analytics events verified\n- Preview approved before production\n";
}

function workflowYaml(): string {
  return `name: WebGenie Quality Gate\n\non:\n  pull_request:\n  push:\n    branches: [main]\n\njobs:\n  quality:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 20\n          cache: npm\n      - run: npm ci\n      - run: npm run typecheck --if-present\n      - run: npm run lint --if-present\n      - run: npm run build\n`;
}

export function generateDeliveryPackage(input: DeliveryInput): DeliveryPackage {
  const files: DeliveryFile[] = [
    jsonFile("webgenie/blueprint.json", input.blueprint, "Canonical website implementation blueprint"),
    markdownFile("README.md", buildReadme(input), "Implementation entry point"),
    markdownFile(`handoff/${input.target.toUpperCase()}_START_HERE.md`, targetHandoff(input.target, input.project.name), "Target-specific execution guide")
  ];

  if (input.content) files.push(jsonFile("webgenie/content.json", input.content, "Generated page copy and SEO content"));
  if (input.orchestration) files.push(jsonFile("webgenie/specialist-review.json", input.orchestration, "Multi-agent production readiness review"));
  if (input.prompts) {
    files.push(jsonFile("webgenie/prompt-package.json", input.prompts, "Structured builder prompt package"));
    for (const document of input.prompts.documents) {
      files.push(markdownFile(`prompts/${document.filename}`, document.markdown, `${document.title} prompt`));
    }
  }

  if (input.target === "github") files.push({ path: ".github/workflows/quality.yml", content: workflowYaml(), contentType: "yaml", purpose: "Pull-request quality gate" });
  if (input.target === "vercel") files.push(jsonFile("vercel.json", { framework: "nextjs" }, "Vercel project configuration"));
  if (input.target === "netlify") files.push({ path: "netlify.toml", content: '[build]\n  command = "npm run build"\n  publish = ".next"\n', contentType: "yaml", purpose: "Netlify build configuration starting point" });
  if (input.target === "claude_code") files.push(markdownFile("CLAUDE.md", targetHandoff("claude_code", input.project.name), "Claude Code repository instructions"));

  const manifest = {
    schemaVersion: "1.0" as const,
    deliveryId: input.deliveryId,
    projectId: input.project.id,
    projectName: input.project.name,
    target: input.target,
    generatedAt: new Date().toISOString(),
    sourceArtifacts: {
      blueprintId: input.blueprintId,
      contentPackageId: input.contentPackageId,
      promptPackageId: input.promptPackageId,
      orchestrationRunId: input.orchestrationRunId
    },
    implementation: {
      framework: input.prompts?.manifest.framework ?? "Next.js / target-builder native output",
      packageManager: "npm",
      buildCommand: "npm run build",
      outputMode: deliveryTargetProfiles[input.target].mode,
      environmentVariables: ["NEXT_PUBLIC_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_ANON_KEY"]
    },
    files: files.map((file) => ({ path: file.path, purpose: file.purpose, bytes: Buffer.byteLength(file.content) })),
    handoffChecklist: [
      "Confirm final brand assets and business facts",
      "Resolve all critical specialist findings",
      "Implement and test the primary conversion path",
      "Verify responsive behavior and accessibility",
      "Validate SEO metadata and structured data",
      "Approve preview before production release"
    ]
  };
  files.unshift(jsonFile("webgenie/manifest.json", manifest, "Delivery manifest and source traceability"));
  return { manifest, files, instructions: manifest.handoffChecklist };
}
