import { Resend } from "resend";
import { createHash } from "node:crypto";

/**
 * Actually delivers the /invite/[token] link generated by
 * api/team/invite and api/partners/invite — those routes always return
 * the link so the admin can still copy/text it by hand as a fallback, but
 * until now nothing ever emailed it. Per CLAUDE.md: "Invites stored, never
 * sent. Send manually." Same Resend integration and best-effort-never-
 * throw discipline as lib/auth/reset-email.ts (the closest existing
 * pattern — also a real, single-use Supabase-adjacent link delivered by
 * email) and lib/vibelabs/welcome-email.ts.
 */
const resend = new Resend(process.env.RESEND_API_KEY);
const FROM = `WebGenie AI <notify@${process.env.RESEND_EMAIL_DOMAIN ?? "mail.vibelabsagency.com"}>`;

export async function sendTeamInviteEmail(input: {
  email: string;
  url: string;
  role: "admin" | "editor" | "viewer" | "partner";
  organizationName: string;
}) {
  const subject =
    input.role === "partner"
      ? `You've been invited to the ${input.organizationName} partner portal`
      : `You've been invited to join ${input.organizationName} on WebGenie AI`;

  const html =
    input.role === "partner"
      ? `<p>You've been invited to the referral partner portal for <strong>${input.organizationName}</strong>.</p>
         <p><a href="${input.url}">Click here to set up your login</a>. This link works once and expires in 7 days.</p>`
      : `<p>You've been invited to join <strong>${input.organizationName}</strong> on WebGenie AI as a${input.role === "admin" ? "n" : ""} ${input.role}.</p>
         <p><a href="${input.url}">Click here to accept and set up your login</a>. This link works once and expires in 7 days.</p>`;

  // Keyed off the link itself — a retry of the same invite (a resend
  // click, a webhook-style redelivery if this is ever called from one)
  // doesn't double-send, but a genuinely new invite to the same email
  // later (a fresh token) still sends its own email.
  const linkHash = createHash("sha256").update(input.url).digest("hex").slice(0, 16);

  const { error } = await resend.emails.send(
    { from: FROM, to: [input.email], subject, html },
    { idempotencyKey: `team-invite/${linkHash}` }
  );

  if (error) {
    console.error("Failed to send team invite email:", error);
  }
}
