import type { ReactNode } from "react";
import Link from "next/link";
import Image from "next/image";
import { CheckCircle2 } from "lucide-react";
import { Logo } from "@/components/shell";
import { SAMPLE_BUSINESSES } from "@/lib/sitegen/samples";

/**
 * P0 (centering pass): rebuilt as ONE centered, bounded composition
 * (`.panel` -- the same rounded/border/shadow surface used everywhere
 * else, so there's no separate visual language to maintain) capped at
 * max-w-[1160px], instead of the previous edge-to-edge lg:grid-cols-2
 * spanning the full viewport width. On an ultra-wide screen the earlier
 * version stretched the form all the way to the left edge and the value
 * panel all the way to the right, so neither felt centered; now the whole
 * two-column composition reads as one balanced, centered object, closer
 * to how vibelabsagency.com frames its own "Meet Vivi" panel. Purely
 * presentational: every page keeps its own handleSubmit, Supabase call,
 * redirect, and validation exactly as it was -- see the page-level diffs.
 * Mobile still shows the form first with the value panel hidden below
 * `lg`, per the task's "prioritize the form" guidance.
 *
 * P0 (iframe-overload correction): the value panel previously loaded a
 * live iframe of a generated site on every login/signup/forgot-password/
 * reset-password page view -- a full generated-site document, running its
 * own scripts, just to sit next to a form. Replaced with the same static,
 * pre-optimized screenshot every other public page now uses (see
 * public/sample-previews/, scripts/generate-sample-thumbnails.mjs). The
 * form itself was never inside that iframe and is unaffected either way.
 */
const REASSURANCE = [
  "Evidence-backed opportunity, not a guess",
  "Human-executed outreach — WebGenie never contacts anyone for you",
  "Start free, no credit card required",
];

export function AuthShell({ children }: { children: ReactNode }) {
  const previewBusiness = SAMPLE_BUSINESSES.find((b) => b.id === "sample-dentist")!;

  return (
    <main className="grid min-h-screen place-items-center px-4 py-10 sm:px-6">
      <div className="panel w-full max-w-[1160px] overflow-hidden lg:grid lg:grid-cols-2">
        <div className="flex flex-col justify-center p-6 sm:p-10 lg:p-12">
          <div className="mx-auto w-full max-w-md">
            <Logo />
            {children}
            <p className="mt-8 text-sm text-faint">
              <Link href="/" className="focus-ring rounded underline decoration-dotted underline-offset-4 hover:text-muted">
                ← Back to WebGenie
              </Link>
            </p>
          </div>
        </div>

        <div className="relative hidden overflow-hidden border-l border-hairline bg-canvas/60 lg:flex lg:flex-col lg:justify-center lg:p-12">
          <div
            className="pointer-events-none absolute inset-0 bg-grid-fade opacity-[0.25]"
            style={{ backgroundSize: "56px 56px", maskImage: "radial-gradient(600px 320px at 50% 20%, #000, transparent)" }}
            aria-hidden
          />
          <div className="relative mx-auto w-full max-w-sm">
            <div className="relative h-56 w-full overflow-hidden rounded-panel border border-hairline bg-white shadow-panel">
              <Image
                src="/sample-previews/dentist.jpg"
                alt={`Preview of the generated demo site for ${previewBusiness.name}, a dental practice in ${previewBusiness.city}, ${previewBusiness.state}`}
                fill
                sizes="(min-width: 1024px) 384px, 0px"
                className="object-cover object-top"
              />
            </div>
            <p className="mt-2 text-sm text-faint">Illustrative example — a real demo site, generated by WebGenie.</p>

            <ul className="mt-8 space-y-3">
              {REASSURANCE.map((item) => (
                <li key={item} className="flex items-start gap-2.5 text-sm text-ink/80">
                  <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-signal-good" aria-hidden />
                  {item}
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </main>
  );
}
