import type { ReactNode } from "react";
import Link from "next/link";
import { CheckCircle2 } from "lucide-react";
import { Logo } from "@/components/shell";
import { SAMPLE_BUSINESSES } from "@/lib/sitegen/samples";
import { demoSiteUrl } from "@/lib/sitegen/encode";

/**
 * Public SaaS Impeccable rebuild (Phase 8): shared visual wrapper for
 * login/signup/forgot-password/reset-password. Purely presentational --
 * every page keeps its own handleSubmit, Supabase call, redirect, and
 * validation exactly as it was; this only replaces the outer
 * `<main><Panel>` centering with a restrained split layout (form column +
 * a real-product value panel), collapsing to form-only below `lg` per the
 * task's mobile guidance ("prioritize the form, remove nonessential promo
 * content").
 */
const REASSURANCE = [
  "Evidence-backed opportunity, not a guess",
  "Human-executed outreach — WebGenie never contacts anyone for you",
  "7-day full-access trial, no credit card required",
];

export function AuthShell({ children }: { children: ReactNode }) {
  const previewBusiness = SAMPLE_BUSINESSES.find((b) => b.id === "sample-dentist")!;
  const previewUrl = demoSiteUrl(previewBusiness, { by: "WebGenie AI", sample: true });

  return (
    <main className="grid min-h-screen lg:grid-cols-2">
      <div className="flex flex-col justify-center px-6 py-12 sm:px-12">
        <div className="mx-auto w-full max-w-md">
          <Logo />
          {children}
          <p className="mt-8 text-sm text-faint">
            <Link href="/" className="focus-ring rounded underline decoration-dotted underline-offset-4 hover:text-muted">
              ← Back to WebGenie
            </Link>
          </p>
        </div>
      </div>

      <div className="relative hidden overflow-hidden border-l border-hairline bg-canvas/60 lg:flex lg:flex-col lg:justify-center lg:p-12">
        <div
          className="pointer-events-none absolute inset-0 bg-grid-fade opacity-[0.25]"
          style={{ backgroundSize: "56px 56px", maskImage: "radial-gradient(600px 320px at 50% 20%, #000, transparent)" }}
          aria-hidden
        />
        <div className="relative mx-auto w-full max-w-sm">
          <div className="overflow-hidden rounded-panel border border-hairline bg-white shadow-panel">
            <div className="relative h-56 w-full overflow-hidden bg-white">
              <iframe
                src={previewUrl}
                title={`Live preview of a generated demo site for ${previewBusiness.name}`}
                loading="lazy"
                tabIndex={-1}
                aria-hidden
                className="pointer-events-none origin-top-left"
                style={{ width: "400%", height: "400%", transform: "scale(0.25)", border: "none" }}
              />
            </div>
          </div>
          <p className="mt-2 text-sm text-faint">Illustrative example — a real demo site, generated by WebGenie.</p>

          <ul className="mt-8 space-y-3">
            {REASSURANCE.map((item) => (
              <li key={item} className="flex items-start gap-2.5 text-sm text-ink/80">
                <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-signal-good" aria-hidden />
                {item}
              </li>
            ))}
          </ul>
        </div>
      </div>
    </main>
  );
}
