import { notFound } from "next/navigation";
import { PageShell } from "@/components/shell";
import { approveOrchestrationAction, rejectOrchestrationAction } from "@/app/actions";
import { createClient } from "@/lib/supabase/server";
import type { OrchestrationRunOutput } from "@/lib/orchestration/types";

const badge: Record<string, string> = { critical: "bg-red-950 text-red-300", high: "bg-orange-950 text-orange-300", medium: "bg-amber-950 text-amber-300", low: "bg-slate-800 text-slate-300" };

export default async function OrchestrationPage({ params }: { params: Promise<{ id: string; runId: string }> }) {
  const { id, runId } = await params;
  const supabase = await createClient();
  const { data: run } = await supabase.from("orchestration_runs").select("id,status,overall_score,overall_confidence,blocking_findings,approval_note,output,created_at").eq("id", runId).eq("project_id", id).maybeSingle();
  if (!run?.output) notFound();
  const output = run.output as OrchestrationRunOutput;
  return <PageShell><div className="space-y-8">
    <section><a href={`/projects/${id}`} className="text-sm text-indigo-300">← Back to project</a><p className="mt-6 text-sm uppercase tracking-[0.2em] text-fuchsia-300">Multi-agent review</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-4xl font-semibold">Production readiness</h1><p className="mt-2 text-slate-400">Eight specialist agents reviewed the blueprint, content, and implementation package.</p></div><span className="rounded-full bg-slate-800 px-4 py-2 text-sm capitalize">{run.status.replace("_", " ")}</span></div></section>
    <section className="grid gap-4 md:grid-cols-3"><Metric label="Overall score" value={`${run.overall_score}/100`}/><Metric label="Confidence" value={`${run.overall_confidence}%`}/><Metric label="Blocking findings" value={String(run.blocking_findings)}/></section>
    <section className="grid gap-4 lg:grid-cols-2">{output.reviews.map((review)=><article key={review.agent} className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><div className="flex justify-between"><h2 className="text-xl font-semibold capitalize">{review.agent} agent</h2><span className="text-sm">{review.score}/100</span></div><p className="mt-3 text-sm text-slate-400">{review.summary}</p><div className="mt-5 space-y-3">{review.findings.length ? review.findings.map((finding)=><div key={finding.id} className="rounded-xl border border-slate-800 bg-slate-950/50 p-4"><span className={`rounded-full px-2 py-1 text-xs uppercase ${badge[finding.severity]}`}>{finding.severity}</span><h3 className="mt-3 font-medium">{finding.title}</h3><p className="mt-2 text-sm text-slate-400">{finding.detail}</p><p className="mt-3 text-sm text-emerald-300">Action: {finding.recommendation}</p></div>) : <p className="rounded-xl bg-emerald-950/40 p-4 text-sm text-emerald-300">No findings.</p>}</div></article>)}</section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-2xl font-semibold">Prioritized revision plan</h2><div className="mt-5 space-y-3">{output.revisionPlan.length ? output.revisionPlan.map((item)=><div key={item.findingId} className="flex gap-4 rounded-xl border border-slate-800 p-4"><span className="font-semibold text-fuchsia-300">{item.priority}</span><div><p className="font-medium capitalize">{item.agent}: {item.action}</p><p className="mt-1 text-sm text-slate-500">{item.rationale}</p></div></div>) : <p className="text-emerald-300">No revisions are required.</p>}</div></section>
    <section className="rounded-2xl border border-fuchsia-900 bg-fuchsia-950/20 p-6"><h2 className="text-xl font-semibold">Approval workflow</h2><div className="mt-5 flex flex-wrap gap-3"><a href={`/api/orchestration-runs/${run.id}/export?format=markdown`} className="rounded-lg border border-slate-700 px-4 py-2 text-sm">Export Markdown</a><a href={`/api/orchestration-runs/${run.id}/export?format=json`} className="rounded-lg border border-slate-700 px-4 py-2 text-sm">Export JSON</a></div>{run.status !== "approved" ? <div className="mt-6 grid gap-4 md:grid-cols-2"><form action={approveOrchestrationAction} className="rounded-xl border border-emerald-900 p-4"><input type="hidden" name="projectId" value={id}/><input type="hidden" name="runId" value={run.id}/><textarea name="note" className="w-full rounded-lg px-3 py-2 text-slate-950" placeholder="Optional approval note"/><button className="mt-3 rounded-lg bg-emerald-300 px-4 py-2 font-medium text-slate-950">Approve handoff</button></form><form action={rejectOrchestrationAction} className="rounded-xl border border-red-900 p-4"><input type="hidden" name="projectId" value={id}/><input type="hidden" name="runId" value={run.id}/><textarea required name="note" className="w-full rounded-lg px-3 py-2 text-slate-950" placeholder="Required revision note"/><button className="mt-3 rounded-lg bg-red-300 px-4 py-2 font-medium text-slate-950">Request revisions</button></form></div> : <p className="mt-5 text-emerald-300">Approved for implementation. {run.approval_note}</p>}</section>
  </div></PageShell>;
}
function Metric({label,value}:{label:string;value:string}) { return <div className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>; }
